### ISSUE TITLE
iOS 11 Bugs

### ISSUE THREAD

**Issue by evgenmedia** [swiftcodex/Swift-Radio-Pro#64] opened 2017-09-24 14:48 UTC
Swift Radio Player have many bugs on iOS 11

- No cover on lock screen
- Radio stops by screen locking

Can you fix it or give advice how to fix it?

**Comment by kryptics** [comment] 2017-09-25 12:29
I can confirm this issue, anyone... Any ideas how to fix? Thanks!

**Comment by swiftcodex** [comment] 2017-09-27 21:31
Have you tried the new Apple Music API?

**Comment by kryptics** [comment] 2017-09-27 21:39
I'll check that out thx Matt, in what particular file do you up date the API...?

**Comment by swiftcodex** [comment] 2017-09-27 21:57
MusicKit API is if you need to stream from Apple Music or the audio on a device. If you're using the public master branch, I believe that is still using the MoviePlayer? I suspect the metaDataDidUpdate might have been depreciated. Without looking, the code that did update the lock screen would be in the NowPlayingController and would probably be labeled something like MetaData Notification

**Comment by swiftcodex** [comment] 2017-09-27 22:08
I suspect experimenting with this might lead to the right path? https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter

**Comment by swiftcodex** [comment] 2017-09-27 22:16
Interestingly enough, I'm not having those issues. I just made sure and pulled the latest code. And, the album art and song appears in the cover sheet in iOS 11. :/

**Comment by evgenmedia** [comment] 2017-09-27 22:27
The cover does not appear if automatic playback is enabled when the application starts
But everything appears (including in the control center), if you stop playback and start it again

**Comment by kryptics** [comment] 2017-09-27 22:51
Mmmm - ok this must just be just a minor bug - when you hit play on the app it pays fine. when you close it (power button) and open it again nothing shows up on the home screen, however, if you go to control center it doesn't show as if the radio is playing, BUT when u hit the play button twice and go back to the home screen it shows up! that is so weird...

**Comment by swiftcodex** [comment] 2017-09-27 23:22
Might be a concurrency issue. If I had the luxury of time, I would rewrite much of this app. It is starting to show its age...

**Comment by gazmac** [comment] 2017-10-20 12:39
swiftcodex - are you testing with the AV version? Planning to migrate to AV. Is anyone having issues with the AV version on iOS 11?

**Comment by fethica** [comment] 2017-10-20 14:10
Hey @gazmac , @joemcmahon has updated the AVPlayer branch to Xcode 9/Swift 4, the master will be switching to AV very soon :)

**Comment by swiftcodex** [comment] 2017-10-21 02:40
@joemcmahaon, @fethica - how do you guys feel about adding an AVPlayer wrapper like this to the code? https://github.com/delannoyk/AudioPlayer  OR, would you like to keep this repo using just the basic Apple stuff?

**Comment by joemcmahon** [comment] 2017-10-21 03:15
Hugely for this. I was about to start working on the connection stuff
myself but this would take care of it.

**Comment by swiftcodex** [comment] 2017-10-21 07:34
@joemcmahon - def not trying to steal your thunder. if you want to add that library to the repo, feel free (as long as @fethica is cool with it?)

**Comment by fethica** [comment] 2017-10-21 16:07
@swiftcodex , @joemcmahon Yes! I was going to create our own wrapper, but this one looks very complete :) We can add it now and optimized later to fit our needs 👍

**Comment by vfmradio** [comment] 2017-11-02 12:00
In ios11, when the track name in Cyrillic appears, the application drops. In this case, ios10 worked. Can you help?

**Comment by fethica** [comment] 2017-11-02 13:22
Hey @vfmradio , did the commit you mention works on iOS 11 ? If not I will check this and let you know if I find a working solution.

**Comment by swiftcodex** [comment] 2017-11-04 21:06
Closing this issue because there is another issue open regarding Cyrillic text.

**Closed by swiftcodex** 2017-11-04 21:06 UTC
